spring.application.name=Parking
spring.datasource.url=jdbc:oracle:thin:@192.168.0.202:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=270402
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
