CREATE TABLE vehicle_type (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(50)
)

CREATE TABLE spot_status (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(30) NOT NULL
);

CREATE TABLE parking_spot (
    spot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id NUMBER,
    status_id NUMBER,
    spot_number NUMBER,
    CONSTRAINT fk_spot_type FOREIGN KEY (type_id) REFERENCES vehicle_type(type_id),
    CONSTRAINT fk_spot_status FOREIGN KEY (status_id) REFERENCES spot_status(status_id)
);

CREATE TABLE pricing_list (
    rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id NUMBER,
    hourly_price NUMBER(10,2),
    minimum_time NUMBER,    

    CONSTRAINT fk_pricing_type FOREIGN KEY (type_id) REFERENCES vehicle_type(type_id)
)

CREATE TABLE vehicle (
    vehicle_plate VARCHAR2(20) PRIMARY KEY,
    type_id NUMBER,
    model VARCHAR2(50),
    color VARCHAR2(30),

    CONSTRAINT fk_vehicle_type_id FOREIGN KEY (type_id) REFERENCES vehicle_type(type_id)
)

CREATE TABLE ticket_status (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(30) NOT NULL
);

CREATE TABLE parking_ticket (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_plate VARCHAR2(20),
    spot_id NUMBER,
    rule_id NUMBER,
    ticket_status_id NUMBER,
    entry_time TIMESTAMP,
    exit_time TIMESTAMP,
    total_fee NUMBER(10,2),

    CONSTRAINT fk_ticket_vehicle_plate FOREIGN KEY (vehicle_plate) REFERENCES vehicle(vehicle_plate),
    CONSTRAINT fk_ticket_spot FOREIGN KEY (spot_id) REFERENCES parking_spot(spot_id),
    CONSTRAINT fk_ticket_rule FOREIGN KEY (rule_id) REFERENCES pricing_list(rule_id),
    CONSTRAINT fk_ticket_status FOREIGN KEY (ticket_status_id) REFERENCES ticket_status(status_id)
)

CREATE INDEX idx_ticket_plate ON parking_ticket(vehicle_plate);
CREATE INDEX idx_ticket_spot ON parking_ticket(spot_id);
CREATE INDEX idx_ticket_rule ON parking_ticket(rule_id);